### ISSUE TITLE
[Feat] Mark API 연결

### ISSUE THREAD

**Issue by hyemib** [Team-C7Z/Mappilogue_iOS#114]
## 💡 todo

- [ ] 기록 생성하기
- [ ] 기록 삭제하기
- [ ] 기록 수정하기
- [ ] 특정 기록 조회하기
- [ ] 특정 카테고리의 기록 조회하기
- [ ] 특정 일정의 장소 조회하기
