### ISSUE TITLE
[Feat] 기록 - 기록 리스트 UI 구현

### ISSUE THREAD

**Issue by hyemib** [Team-C7Z/Mappilogue_iOS#69]
## 💡 todo

- [x] 나의 기록 리스트
- [x] 카테고리 별 기록 리스트
- [x] 카테고리 별 기록 텅뷰
- [x] 카테고리 이름 수정/삭제
- [x] 카테고리 설정
- [x] 카테고리 추가
