### ISSUE TITLE
[Feat] 기록 - 사진 편집 UI 구현

### ISSUE THREAD

**Issue by hyemib** [Team-C7Z/Mappilogue_iOS#90]
## 💡 todo

- [x] 사진 권한 허용X
- [x] 선택한 사진만 허용
- [x] 모든 사진 허용
- [x] 텍스트 + 이미지 작성
- [x] 대표 사진 지정 및 제거
